### ISSUE TITLE
support for tcp+tls

### ISSUE THREAD

**Issue by mictsi** [micahhausler/logspout-gelf#15]
Hi, 

is it possible for you to add support for TCP+TLS for gelf to secure communications.

Michael

**Comment by karlvr** [comment]
@mictsi I have pulled together code from a few repos and tweaked to get TLS with GELF and logspout https://github.com/karlvr/logspout-gelf and a Docker image for it https://hub.docker.com/r/karlvr/logspout-gelf

**Comment by mictsi** [comment]
@karlvr Thanks, just tested it and it works fine. Closing this issue.
